redis:
  address: localhost:6379
  username: ""
  password: ""
  db: 0
  use_tls: false
  sentinel_master_name: ""
  sentinel_username: ""
  sentinel_password: ""
  sentinel_addresses: []
  cluster_addresses: []
  max_redirects: null
api_key: API77p5xkYYFHH4
api_secret: u1zMOFgduXbslIPZm6fyvPUxVfUB9EJMWrNQocUDpNb
ws_url: ws://localhost:7880
log_level: info
enable_chrome_sandbox: true
cpu_cost:
  room_composite_cpu_cost: 3
  track_composite_cpu_cost: 2
  track_cpu_cost: 1