redis:
  address: localhost:6379
  username: ""
  password: ""
  db: 0
  use_tls: false
  sentinel_master_name: ""
  sentinel_username: ""
  sentinel_password: ""
  sentinel_addresses: []
  cluster_addresses: []
  max_redirects: null
api_key: API77p5xkYYFHH4
api_secret: u1zMOFgduXbslIPZm6fyvPUxVfUB9EJMWrNQocUDpNb
ws_url: ws://localhost:7880
rtmp_port: 1935
whip_port: 8080
http_relay_port: 9090
logging:
  json: false
  level: debug
rtc_config:
  udp_port: 7885
  use_external_ip: false
  enable_loopback_candidate: false
cpu_cost:
  rtmp_cpu_cost: 2.0
  whip_cpu_cost: 2.0
  whip_bypass_transcoding_cpu_cost: 0.1
  url_cpu_cost: 2