port: 7880
bind_addresses:
    - ""
rtc:
  tcp_port: 7881
  port_range_start: 50000
  port_range_end: 60000
  use_external_ip: false
  enable_loopback_candidate: false
redis:
  address: localhost:6379
  username: ""
  password: ""
  db: 0
  use_tls: false
  sentinel_master_name: ""
  sentinel_username: ""
  sentinel_password: ""
  sentinel_addresses: []
  cluster_addresses: []
  max_redirects: null
turn:
  enabled: true
  domain: livekit-turn.myhost.com
  tls_port: 5349
  udp_port: 3478
  external_tls: true
ingress:
  rtmp_base_url: "rtmps://my.domain.com/live"
  whip_base_url: "https://my.domain.com/whip"
keys:
  API77p5xkYYFHH4: u1zMOFgduXbslIPZm6fyvPUxVfUB9EJMWrNQocUDpNb